import type {
  Hospital,
  Interpreter,
  Hotel,
  User,
  Vehicle,
} from "./types";

export const usersSeed: User[] = [
  {
    id: "u_admin",
    email: "admin",
    password: "admin",
    name: "Administrator",
    country: "Korea",
    role: "admin",
    createdAt: new Date().toISOString(),
  },
  {
    id: "u_demo",
    email: "demo@traveler.com",
    password: "demo",
    name: "Jane Traveler",
    country: "USA",
    role: "user",
    createdAt: new Date().toISOString(),
  },
];

export const hospitalsSeed: Hospital[] = [
  {
    id: "h1",
    name: "ID Hospital",
    nameKo: "아이디병원",
    category: "plastic-surgery",
    city: "Seoul",
    district: "Gangnam",
    rating: 4.9,
    reviewCount: 2340,
    priceFrom: 1800,
    image: "https://images.pexels.com/photos/3985296/pexels-photo-3985296.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "One of Korea's leading plastic surgery hospitals, specializing in facial contouring, rhinoplasty, and anti-aging procedures with over 20 years of expertise.",
    descriptionKo: "20년 이상의 경력을 가진 한국 최고의 성형외과. 윤곽, 코, 안티에이징 전문.",
    languages: ["English", "Chinese", "Japanese", "Vietnamese"],
    certifications: ["KFDA", "JCI Affiliate", "KAHMS"],
    doctors: [
      { id: "d1", name: "Dr. Park Sang-hoon", specialty: "Facial Contouring", experience: 22, avatar: "🧑‍⚕️", bio: "Pioneer of V-line surgery with more than 15,000 successful cases." },
      { id: "d2", name: "Dr. Lee Hyun-tae", specialty: "Rhinoplasty", experience: 14, avatar: "👨‍⚕️", bio: "Specializes in revision rhinoplasty and ethnic nose reshaping." },
    ],
    treatments: [
      { id: "t1", name: "Double Eyelid Surgery", nameKo: "쌍커풀 수술", duration: "1h", price: 1800 },
      { id: "t2", name: "Rhinoplasty", nameKo: "코 성형", duration: "2h", price: 4200 },
      { id: "t3", name: "V-Line Jaw Surgery", nameKo: "V라인 턱 수술", duration: "3h", price: 9500 },
      { id: "t4", name: "Facelift", nameKo: "안면거상", duration: "3h", price: 7800 },
    ],
    allowedInterpreters: [],
    allowedHotels: [],
    allowedVehicles: [],
  },
  {
    id: "h2",
    name: "Muse Dermatology",
    nameKo: "뮤즈피부과",
    category: "dermatology",
    city: "Seoul",
    district: "Cheongdam",
    rating: 4.8,
    reviewCount: 1820,
    priceFrom: 120,
    image: "https://images.pexels.com/photos/32260064/pexels-photo-32260064.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "Premium K-beauty dermatology clinic famous for skin boosters, lasers, and non-invasive lifting treatments popular among international visitors.",
    descriptionKo: "스킨부스터, 레이저, 비수술 리프팅으로 유명한 프리미엄 피부과.",
    languages: ["English", "Chinese", "Thai"],
    certifications: ["KFDA", "Restylane Certified"],
    doctors: [
      { id: "d3", name: "Dr. Kim Yuna", specialty: "Skin Rejuvenation", experience: 11, avatar: "👩‍⚕️", bio: "Dermatology specialist focused on natural-looking skin results." },
    ],
    treatments: [
      { id: "t5", name: "Skin Botox", nameKo: "스킨보톡스", duration: "30min", price: 120 },
      { id: "t6", name: "Rejuran Healer", nameKo: "리쥬란 힐러", duration: "45min", price: 380 },
      { id: "t7", name: "Ultherapy Lifting", nameKo: "울쎄라 리프팅", duration: "1h", price: 1400 },
      { id: "t8", name: "Pico Laser", nameKo: "피코 레이저", duration: "40min", price: 260 },
    ],
    allowedInterpreters: [],
    allowedHotels: [],
    allowedVehicles: [],
  },
  {
    id: "h3",
    name: "Gangnam Smile Dental",
    nameKo: "강남스마일치과",
    category: "dentistry",
    city: "Seoul",
    district: "Gangnam",
    rating: 4.7,
    reviewCount: 980,
    priceFrom: 900,
    image: "https://images.pexels.com/photos/19879757/pexels-photo-19879757.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "State-of-the-art dental clinic offering implants, Hollywood smile design, and clear aligners with same-day services available.",
    descriptionKo: "임플란트, 스마일 디자인, 투명 교정을 당일 시술 가능한 최신 치과.",
    languages: ["English", "Japanese"],
    certifications: ["Straumann Partner", "Invisalign Diamond"],
    doctors: [
      { id: "d4", name: "Dr. Choi Minho", specialty: "Implantology", experience: 16, avatar: "🦷", bio: "Certified implant specialist with over 8,000 implant cases." },
    ],
    treatments: [
      { id: "t9", name: "Dental Implant", nameKo: "임플란트", duration: "2h", price: 1200 },
      { id: "t10", name: "Porcelain Veneers", nameKo: "라미네이트", duration: "3h", price: 900 },
      { id: "t11", name: "Invisalign", nameKo: "인비절라인", duration: "consultation", price: 3800 },
      { id: "t12", name: "Teeth Whitening", nameKo: "치아 미백", duration: "1h", price: 280 },
    ],
    allowedInterpreters: [],
    allowedHotels: [],
    allowedVehicles: [],
  },
  {
    id: "h4",
    name: "Woori Orthopedic Center",
    nameKo: "우리정형외과",
    category: "orthopedics",
    city: "Seoul",
    district: "Yeouido",
    rating: 4.8,
    reviewCount: 1240,
    priceFrom: 600,
    image: "https://images.pexels.com/photos/8376138/pexels-photo-8376138.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "Leading orthopedic hospital for joint replacement, spine surgery, and sports medicine with minimally invasive techniques.",
    descriptionKo: "관절, 척추, 스포츠 의학 최소침습 수술 전문 병원.",
    languages: ["English", "Russian", "Mongolian"],
    certifications: ["JCI", "ISO 9001"],
    doctors: [
      { id: "d5", name: "Dr. Jung Ho-seok", specialty: "Joint Replacement", experience: 20, avatar: "🧑‍⚕️", bio: "Pioneer of robotic-assisted knee replacement in Korea." },
    ],
    treatments: [
      { id: "t13", name: "Knee Arthroscopy", nameKo: "무릎 관절경", duration: "1h", price: 2400 },
      { id: "t14", name: "Spine Disc Treatment", nameKo: "척추 디스크", duration: "1.5h", price: 3600 },
      { id: "t15", name: "Shoulder Repair", nameKo: "어깨 수술", duration: "2h", price: 4800 },
      { id: "t16", name: "Sports Rehab", nameKo: "스포츠 재활", duration: "1h/session", price: 120 },
    ],
    allowedInterpreters: [],
    allowedHotels: [],
    allowedVehicles: [],
  },
  {
    id: "h5",
    name: "Hana Premium Checkup",
    nameKo: "하나 프리미엄 검진",
    category: "checkup",
    city: "Seoul",
    district: "Jongno",
    rating: 4.9,
    reviewCount: 650,
    priceFrom: 450,
    image: "https://images.pexels.com/photos/12670300/pexels-photo-12670300.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "Comprehensive health checkup center with same-day results, English reports, and hotel pickup included for international guests.",
    descriptionKo: "당일 결과, 영문 리포트, 공항 픽업이 포함된 종합 건강검진 센터.",
    languages: ["English", "Chinese", "Japanese", "Arabic"],
    certifications: ["AAHRPP", "KFDA"],
    doctors: [
      { id: "d6", name: "Dr. Seo Ji-ah", specialty: "Preventive Medicine", experience: 13, avatar: "👩‍⚕️", bio: "Board-certified preventive medicine specialist." },
    ],
    treatments: [
      { id: "t17", name: "Basic Health Checkup", nameKo: "기본 건강검진", duration: "3h", price: 450 },
      { id: "t18", name: "Premium Full Body", nameKo: "프리미엄 종합검진", duration: "5h", price: 1200 },
      { id: "t19", name: "Cancer Screening", nameKo: "암 정밀 검사", duration: "4h", price: 1800 },
      { id: "t20", name: "Cardiac Screening", nameKo: "심장 정밀 검사", duration: "3h", price: 1500 },
    ],
    allowedInterpreters: [],
    allowedHotels: [],
    allowedVehicles: [],
  },
  {
    id: "h6",
    name: "Renew Plastic Surgery",
    nameKo: "리뉴성형외과",
    category: "plastic-surgery",
    city: "Seoul",
    district: "Apgujeong",
    rating: 4.7,
    reviewCount: 1560,
    priceFrom: 1500,
    image: "https://images.pexels.com/photos/3985296/pexels-photo-3985296.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "Boutique plastic surgery clinic known for natural results in body contouring and breast surgery.",
    descriptionKo: "자연스러운 바디 및 가슴 성형으로 유명한 부티크 성형외과.",
    languages: ["English", "Chinese"],
    certifications: ["KFDA"],
    doctors: [
      { id: "d7", name: "Dr. Ahn Ji-won", specialty: "Body Contouring", experience: 15, avatar: "👩‍⚕️", bio: "Expert in liposuction and body sculpting procedures." },
    ],
    treatments: [
      { id: "t21", name: "Liposuction", nameKo: "지방흡입", duration: "2h", price: 3200 },
      { id: "t22", name: "Breast Augmentation", nameKo: "가슴 성형", duration: "2h", price: 6500 },
      { id: "t23", name: "Tummy Tuck", nameKo: "복부 성형", duration: "3h", price: 5400 },
    ],
    allowedInterpreters: [],
    allowedHotels: [],
    allowedVehicles: [],
  },
];

export const interpretersSeed: Interpreter[] = [
  { id: "i1", name: "Sarah K.", language: "English", flag: "🇺🇸", pricePerDay: 120, rating: 4.9, experience: 6, medical: true },
  { id: "i2", name: "Yuki M.", language: "Japanese", flag: "🇯🇵", pricePerDay: 130, rating: 5.0, experience: 8, medical: true },
  { id: "i3", name: "Chen Wei", language: "Chinese", flag: "🇨🇳", pricePerDay: 120, rating: 4.8, experience: 5, medical: true },
  { id: "i4", name: "Nguyen Linh", language: "Vietnamese", flag: "🇻🇳", pricePerDay: 110, rating: 4.7, experience: 4, medical: false },
  { id: "i5", name: "Alina P.", language: "Russian", flag: "🇷🇺", pricePerDay: 140, rating: 4.9, experience: 7, medical: true },
  { id: "i6", name: "Priya S.", language: "Thai", flag: "🇹🇭", pricePerDay: 115, rating: 4.6, experience: 3, medical: false },
];

export const hotelsSeed: Hotel[] = [
  { id: "ht1", name: "Signiel Seoul", district: "Jamsil", stars: 5, pricePerNight: 420, image: "🏨", amenities: ["Spa", "Pool", "Airport Shuttle", "English Staff"] },
  { id: "ht2", name: "L7 Gangnam", district: "Gangnam", stars: 4, pricePerNight: 180, image: "🏩", amenities: ["Gym", "Rooftop", "Near Clinics", "English Staff"] },
  { id: "ht3", name: "Dormy Inn Seoul", district: "Gangnam", stars: 3, pricePerNight: 95, image: "🛏️", amenities: ["Onsen", "Breakfast", "Near Subway"] },
  { id: "ht4", name: "Four Seasons Seoul", district: "Gwanghwamun", stars: 5, pricePerNight: 580, image: "🏛️", amenities: ["Spa", "Pool", "Concierge", "Recovery Suite"] },
];

export const vehiclesSeed: Vehicle[] = [
  { id: "v1", name: "Genesis G80 Sedan", type: "sedan", capacity: 3, pricePerDay: 150, image: "🚗" },
  { id: "v2", name: "Hyundai Staria Van", type: "van", capacity: 7, pricePerDay: 200, image: "🚐" },
  { id: "v3", name: "Kia Carnival SUV", type: "suv", capacity: 5, pricePerDay: 170, image: "🚙" },
];
